name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download src
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        env: 
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/panda-market
        run: npm run test
        
      

