name: test and deploy

on: 
  push:
    branches:
      - main


jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: panda-market
        ports:
          - 5432:5432
    steps:
      - name: Download src
        uses: actions/checkout@v4

      - name: Setup Node  
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        env: 
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/panda-market,
          PORT: 3000,
          JWT_ACCESS_TOKEN_SECRET: ${{ secrets.CODEIT_JWT_ACCESS_TOKEN_SECRET }},
          JWT_REFRESH_TOKEN_SECRET: ${{ secrets.CODEIT_JWT_REFRESH_TOKEN_SECRET }}  
        run: npm run test

      - name: upload coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download src
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
        
      - name: Install Dependencies
        run: npm install
        
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CODEIT_EC2_HOST }}
          username: ${{ secrets.CODEIT_EC2_USERNAME }}
          key: ${{ secrets.CODEIT_EC2_KEY }}
          port: 22
          script: |
            cd /home/ubuntu/2-sprint-mission/mission_10
            git pull
            npm install --production
            npm run build
            pm2 restart all
      

