name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: panda-market
        ports:
          - 5432:5432
    steps:
      - name: Download src
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install
      
      - name: Run Tests
        env: 
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/panda-market
        run: npm run test
        
      

